# Generated by Django 5.0.3 on 2024-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
